[package]
name = "popsicle_cli"
description = "USB Flasher"
version = "0.1.5"
authors = ["Jeremy Soller <jeremy@system76.com>"]
license = "MIT"
readme = "README.md"
edition = "2018"

[[bin]]
name = "popsicle"
path = "src/main.rs"

[dependencies]
anyhow = "1"
async-std = "1"
better-panic = "0.2"
cascade = "0.1"
clap = "2"
fomat-macros = "0.3"
futures = "0.3"
pbr = "1"
popsicle = { path = ".." }
