[package]
name = "popsicle_gtk"
description = "USB Flasher"
version = "0.2.0"
authors = [ "Michael Aaron Murphy <michael@system76.com>" ]
license = "MIT"
readme = "README.md"
edition = "2018"

[[bin]]
name = "popsicle-gtk"
path = "src/main.rs"

[dependencies]
atomic = "0.4"
bus_writer = "0.1"
bytesize = "1.0.1"
cascade = "0.1"
crossbeam-channel = "0.4"
digest = "0.8"
gdk = "0.13"
glib = "0.10"
gtk = { version = "0.9", features = ["v3_22"] }
hex-view = "0.1"
libc = "0.2"
md-5 = "0.8"
pango = "0.9"
parking_lot = "0.10"
popsicle = { path = ".." }
proc-mounts = "0.2"
pwd = "1"
sha2 = "0.8"
sys-mount = "1"
sysfs-class = "0.1"
async-std = "1.3.0"
